apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kl0t2w9ft-java-springboot
  janus-idp.io/tekton: kl0t2w9ft-java-springboot
  backstage.io/kubernetes-id: kl0t2w9ft-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kl0t2w9ft-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
